using System.Text.Json;
using Azure.Identity;
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using Azure.Storage.Sas;
using Biotrackr.Reporting.Api.Configuration;
using Biotrackr.Reporting.Api.Models;
using Microsoft.Extensions.Options;

namespace Biotrackr.Reporting.Api.Services
{
    public class BlobStorageService(
        IOptions<Settings> settings,
        IConfiguration configuration,
        ILogger<BlobStorageService> logger) : IBlobStorageService
    {
        private const string ContainerName = "reports";
        private const string MetadataFileName = "metadata.json";
        private static readonly TimeSpan DefaultSasExpiry = TimeSpan.FromHours(24);

        // ASI09: Mandatory disclaimer for AI-generated health reports
        private const string ReportDisclaimer =
            "DISCLAIMER: This report was generated by an AI agent. " +
            "All health data should be reviewed by a qualified healthcare professional. " +
            "Do not make medical decisions based solely on this report.";

        private readonly Lazy<BlobServiceClient> _blobServiceClient = new(() =>
        {
            var managedIdentityClientId = configuration.GetValue<string>("managedidentityclientid");
            var credential = new DefaultAzureCredential(new DefaultAzureCredentialOptions
            {
                ManagedIdentityClientId = managedIdentityClientId
            });
            return new BlobServiceClient(new Uri(settings.Value.ReportingBlobStorageEndpoint), credential);
        });

        private BlobServiceClient Client => _blobServiceClient.Value;

        public async Task<string> CreateJobAsync(string reportType, string startDate, string endDate)
        {
            var jobId = Guid.NewGuid().ToString();
            var blobPath = BuildBlobPath(startDate, endDate, reportType);

            var metadata = new ReportMetadata
            {
                JobId = jobId,
                Status = ReportStatus.Generating,
                ReportType = reportType,
                DateRange = new ReportDateRange { Start = startDate, End = endDate }
            };

            await UploadMetadataAsync(blobPath, metadata);
            logger.LogInformation("Created report job {JobId} at {BlobPath}", jobId, blobPath);

            return jobId;
        }

        public async Task UploadReportAsync(
            string jobId,
            byte[] pdfBytes,
            Dictionary<string, byte[]> charts,
            string summary,
            object sourceDataSnapshot)
        {
            var metadata = await GetMetadataAsync(jobId);
            if (metadata is null)
            {
                throw new InvalidOperationException($"Job {jobId} not found");
            }

            var blobPath = BuildBlobPath(metadata.DateRange.Start, metadata.DateRange.End, metadata.ReportType);
            var containerClient = Client.GetBlobContainerClient(ContainerName);
            var artifacts = new List<string>();

            // Upload PDF
            if (pdfBytes.Length > 0)
            {
                var pdfBlobName = $"{blobPath}/report.pdf";
                var pdfBlob = containerClient.GetBlobClient(pdfBlobName);
                await pdfBlob.UploadAsync(new BinaryData(pdfBytes), overwrite: true);
                artifacts.Add("report.pdf");
                logger.LogInformation("Uploaded PDF for job {JobId}: {BlobName}", jobId, pdfBlobName);
            }

            // Upload charts
            foreach (var (chartName, chartBytes) in charts)
            {
                var chartBlobName = $"{blobPath}/{chartName}";
                var chartBlob = containerClient.GetBlobClient(chartBlobName);
                await chartBlob.UploadAsync(new BinaryData(chartBytes), overwrite: true);
                artifacts.Add(chartName);
                logger.LogInformation("Uploaded chart for job {JobId}: {BlobName}", jobId, chartBlobName);
            }

            // Update metadata
            metadata.Status = ReportStatus.Generated;
            metadata.GeneratedAt = DateTimeOffset.UtcNow;
            metadata.Summary = $"{ReportDisclaimer}\n\n{summary}";
            metadata.Artifacts = artifacts;
            metadata.SourceDataSnapshot = sourceDataSnapshot;

            await UploadMetadataAsync(blobPath, metadata);
            logger.LogInformation("Report job {JobId} completed with {ArtifactCount} artifacts", jobId, artifacts.Count);
        }

        public async Task UpdateJobStatusAsync(string jobId, string status, string? error = null)
        {
            var metadata = await GetMetadataAsync(jobId);
            if (metadata is null)
            {
                throw new InvalidOperationException($"Job {jobId} not found");
            }

            metadata.Status = status;
            if (error is not null)
            {
                metadata.Error = error;
            }

            var blobPath = BuildBlobPath(metadata.DateRange.Start, metadata.DateRange.End, metadata.ReportType);
            await UploadMetadataAsync(blobPath, metadata);
            logger.LogInformation("Updated job {JobId} status to {Status}", jobId, status);
        }

        public async Task<ReportMetadata?> GetMetadataAsync(string jobId)
        {
            var containerClient = Client.GetBlobContainerClient(ContainerName);

            await foreach (var blob in containerClient.GetBlobsAsync(prefix: ""))
            {
                if (!blob.Name.EndsWith($"/{MetadataFileName}"))
                    continue;

                var blobClient = containerClient.GetBlobClient(blob.Name);
                var content = await blobClient.DownloadContentAsync();
                var metadata = JsonSerializer.Deserialize<ReportMetadata>(content.Value.Content.ToString());

                if (metadata?.JobId == jobId)
                    return metadata;
            }

            return null;
        }

        public async Task<string> GetReportSasUrlAsync(string blobPath)
        {
            var containerClient = Client.GetBlobContainerClient(ContainerName);
            var blobClient = containerClient.GetBlobClient(blobPath);

            var userDelegationKey = await Client.GetUserDelegationKeyAsync(
                DateTimeOffset.UtcNow,
                DateTimeOffset.UtcNow.Add(DefaultSasExpiry));

            var sasBuilder = new BlobSasBuilder
            {
                BlobContainerName = ContainerName,
                BlobName = blobPath,
                Resource = "b",
                ExpiresOn = DateTimeOffset.UtcNow.Add(DefaultSasExpiry)
            };
            sasBuilder.SetPermissions(BlobSasPermissions.Read);

            var sasToken = sasBuilder.ToSasQueryParameters(userDelegationKey, Client.AccountName);
            return $"{blobClient.Uri}?{sasToken}";
        }

        public async Task<List<ReportMetadata>> ListReportsAsync(
            string? reportType = null,
            string? startDate = null,
            string? endDate = null)
        {
            var containerClient = Client.GetBlobContainerClient(ContainerName);
            var reports = new List<ReportMetadata>();

            await foreach (var blob in containerClient.GetBlobsAsync(prefix: ""))
            {
                if (!blob.Name.EndsWith($"/{MetadataFileName}"))
                    continue;

                var blobClient = containerClient.GetBlobClient(blob.Name);
                var content = await blobClient.DownloadContentAsync();
                var metadata = JsonSerializer.Deserialize<ReportMetadata>(content.Value.Content.ToString());

                if (metadata is null) continue;

                if (reportType is not null && metadata.ReportType != reportType)
                    continue;

                if (startDate is not null && string.Compare(metadata.DateRange.Start, startDate, StringComparison.Ordinal) < 0)
                    continue;

                if (endDate is not null && string.Compare(metadata.DateRange.End, endDate, StringComparison.Ordinal) > 0)
                    continue;

                reports.Add(metadata);
            }

            return reports.OrderByDescending(r => r.GeneratedAt).ToList();
        }

        private async Task UploadMetadataAsync(string blobPath, ReportMetadata metadata)
        {
            var containerClient = Client.GetBlobContainerClient(ContainerName);
            var metadataBlobName = $"{blobPath}/{MetadataFileName}";
            var metadataBlob = containerClient.GetBlobClient(metadataBlobName);

            var json = JsonSerializer.Serialize(metadata, new JsonSerializerOptions { WriteIndented = true });
            await metadataBlob.UploadAsync(new BinaryData(json), overwrite: true);
        }

        private static string BuildBlobPath(string startDate, string endDate, string reportType)
        {
            var timestamp = DateTimeOffset.UtcNow.ToString("yyyyMMdd-HHmmss");
            return $"{startDate}_{endDate}/{reportType}/{timestamp}";
        }
    }
}
