name: Deploy Core Biotrackr Infrastructure

on:
    pull_request:
        branches:
            - main
        paths:
            - 'infra/core/*'

permissions:
    contents: read
    id-token: write
    pull-requests: write

jobs:
    lint:
        name: Run Linter
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              name: Checkout repository code

            - name: Run Bicep Linter
              run: az bicep build --file ./infra/core/main.bicep

    validate:
        needs: lint
        name: Validate Template
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              name: Checkout repository code

            - uses: azure/login@v2
              name: Login to Azure
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - uses: azure/arm-deploy@v2
              name: Run preflight validation
              with:
                scope: 'subscription'
                deploymentName: ${{ github.run_number }}
                template: './infra/core/main.bicep'
                parameters: './infra/core/main.dev.bicepparam'
                deploymentMode: Validate

    preview:
        needs: validate
        name: Preview Changes
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              name: Checkout repository code

            - uses: azure/login@v2
              name: Login to Azure
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - uses: Azure/cli@v2
              name: Run what-if
              with:
                inlineScript: |
                    az deployment sub what-if --location australiaeast --template-file ./infra/core/main.bicep --parameters ./infra/core/main.dev.bicepparam

    deploy:
        needs: preview
        name: Deploy Template
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              name: Checkout repository code

            - uses: azure/login@v2
              name: Login to Azure
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
            - uses: azure/arm-deploy@v2
              name: Run preflight validation
              with:
                scope: 'subscription'
                deploymentName: ${{ github.run_number }}
                template: './infra/core/main.bicep'
                parameters: './infra/core/main.dev.bicepparam'
                failOnStdErr: false