name: Deploy Core Biotrackr Infrastructure

on:
    pull_request:
        branches:
            - main
        paths:
            - 'infra/core/**'
            - 'infra/modules/**'

permissions:
    contents: read
    id-token: write
    pull-requests: write

jobs:
    lint:
        name: Run Bicep Linter
        uses: willvelida/biotrackr/.github/workflows/template-bicep-linter.yml@main
        with:
          template-file: './infra/core/main.bicep'

    validate:
        needs: lint
        name: Validate Template
        uses: willvelida/biotrackr/.github/workflows/template-bicep-validate.yml@main
        with:
          template-file: './infra/core/main.bicep'
          parameters-file: './infra/core/main.dev.bicepparam'
          scope: resourceGroup
        secrets:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resource-group-name: ${{ secrets.AZURE_RG_NAME_DEV }}

    preview:
        needs: validate
        name: Preview Changes
        uses: willvelida/biotrackr/.github/workflows/template-bicep-whatif.yml@main
        with:
          template-file: './infra/core/main.bicep'
          parameters-file: './infra/core/main.dev.bicepparam'
          scope: resourceGroup
        secrets:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resource-group-name: ${{ secrets.AZURE_RG_NAME_DEV }}

    deploy-dev:
        needs: preview
        name: Deploy Template to Dev
        uses: willvelida/biotrackr/.github/workflows/template-bicep-deploy.yml@main
        with:
          template-file: './infra/core/main.bicep'
          parameters-file: './infra/core/main.dev.bicepparam'
          scope: resourceGroup
          environment: dev
        secrets:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resource-group-name: ${{ secrets.AZURE_RG_NAME_DEV }}