name: PSRule Bicep Analysis

on:
    push:
        branches:
            - main
        paths:
            - 'infra/**'
            - 'ps-rule.yaml'
    pull_request:
        branches:
            - main
        paths:
            - 'infra/**'
            - 'ps-rule.yaml'

permissions:
    contents: read
    security-events: write

jobs:
    analyze:
        name: Analyze Bicep
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

            - name: Analyze Bicep files
              uses: microsoft/ps-rule@46451b8f5258c41beb5ae69ed7190ccbba84112c # v2.9.0
              continue-on-error: true
              with:
                modules: 'PSRule.Rules.Azure'
                outputFormat: Sarif
                outputPath: results.sarif

            - name: Upload SARIF
              uses: github/codeql-action/upload-sarif@95e58e9a2cdfd71adc6e0353d5c52f41a045d225 # v4
              if: success() || failure()
              with:
                sarif_file: results.sarif
