name: Run ACA Api Integration Tests

on:
    workflow_call:
        inputs:
            dotnet-version:
                description: 'The version of .NET to use'
                required: true
                type: string
            working-directory:
                description: 'The working directory to run the tests'
                required: true
                type: string
            test-project:
                description: 'The Integration Test Project to run'
                required: true
                type: string
            api-name:
                description: 'The name of the Api that will be tested'
                required: true
                type: string
        secrets:
            client-id:
                required: true
            tenant-id:
                required: true
            subscription-id:
                required: true
            resource-group-name:
                required: true

jobs:
    run-integration-tests:
        name: Run Integration Tests
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{ inputs.working-directory }}

        steps:
            - name: Checkout Repository code
              uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

            - uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43 # v3.0.0
              name: Login to Azure
              with:
                client-id: ${{ secrets.client-id }}
                tenant-id: ${{ secrets.tenant-id }}
                subscription-id: ${{ secrets.subscription-id }}

            - name: Get API URL
              id: getapiurl
              run: |
                echo "Installing containerapp extension"
                az extension add -n containerapp --yes
                apiURL=$(az containerapp revision list -g ${{ secrets.resource-group-name }} -n ${{ inputs.api-name }} --query 'reverse(sort_by([].{Revision:name,Replicas:properties.replicas,Active:properties.active,Created:properties.createdTime,FQDN:properties.fqdn}[?Active!=`false`], &Created))| [0].FQDN' -o tsv)
                echo "apiURL=$apiURL" >> "$GITHUB_OUTPUT"

            - name: Get Cosmos DB endpoint
              id: getcosmosendpoint
              run: |
                cosmosurl=$(az cosmosdb list --resource-group ${{ secrets.resource-group-name }} --query "[0].documentEndpoint" --output tsv)
                echo "cosmosurl=$cosmosurl" >> "$GITHUB_OUTPUT"

            - name: Get App Config endpoint
              id: getappconfigendpoint
              run: |
                appconfigurl=$(az appconfig list --resource-group ${{ secrets.resource-group-name }} --query "[0].endpoint" --output tsv)
                echo "appconfigurl=$appconfigurl" >> "$GITHUB_OUTPUT"
            
            - name: Setup .NET ${{ inputs.dotnet-version }}
              uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5
              with:
                dotnet-version: ${{ inputs.dotnet-version }}
            
            - name: Install dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --no-restore --verbosity normal

            - name: Test
              run: dotnet test ${{ inputs.test-project }} --no-build --verbosity normal  --logger trx
              env:
                apiurl: "https://${{ steps.getapiurl.outputs.apiURL }}"
                azureappconfigendpoint: ${{ steps.getappconfigendpoint.outputs.appconfigurl }}
                managedidentityclientid: ${{ secrets.client-id }}
                cosmosdbendpoint: ${{ steps.getcosmosendpoint.outputs.cosmosurl }}
                tenantid: ${{ secrets.tenant-id }}               