name: Preview Bicep Deployment

on:
    workflow_call:
        inputs:
            template-file:
                required: true
                type: string
            parameters-file:
                required: true
                type: string
            scope:
                required: true
                type: string
        secrets:
            client-id:
                required: true
            tenant-id:
                required: true
            subscription-id:
                required: true
            resource-group-name:
                required: true

jobs:
    preview:
        name: Preview Bicep Template Deployment
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
          name: Checkout Repository Code

        - uses: azure/login@v2
          name: Login to Azure
          with:
            client-id: ${{ secrets.client-id }}
            tenant-id: ${{ secrets.tenant-id }}
            subscription-id: ${{ secrets.subscription-id }}

        - uses: Azure/cli@v2
          name: Run What-If Preview
          with:
            inlineScript: |
                az deployment group what-if --resource-group ${{ secrets.resource-group-name }} --template-file ${{ inputs.template-file }} --parameters ${{ inputs.parameters-file }}

        - uses: azure/bicep-deploy@v2
          name: Perform What-If
          with:
            type: deployment
            operation: whatIf
            scope: ${{ inputs.scope }}
            validation-level: 'providerNoRbac'
            subscription-id: ${{ secrets.subscription-id }}
            resource-group-name: ${{ secrets.resource-group-name }}
            name: ${{ github.run_number }}
            template-file: ${{ inputs.template-file }}
            parameters-file: ${{ inputs.parameters-file }}